import React,{useEffect,useRef,useState} from 'react'
import {ArrowUpRight,BarChart3,BriefcaseBusiness,Check,ClipboardList,Clock3,LayoutDashboard,LogOut,Mail,MapPin,RefreshCw,Search,ShieldCheck,Users,X} from 'lucide-react'
import JobPhotos from './JobPhotos'
import {STATUS,metrics,filterJobs,createdDate,ageDays,overdue} from './adminMetrics'
import './admin.css'

const number=n=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:1}).format(n)
const date=value=>value?new Date(value).toLocaleDateString('de-DE'):'Nicht angegeben'
function Badge({status}){return <span className={`ad-badge ad-${status}`}>{STATUS[status]}</span>}
function Ranking({items,empty}){const max=items[0]?.[1]||1;return items.length?<div className="ad-ranking">{items.slice(0,6).map(([label,count])=><div key={label}><div><span>{label}</span><b>{number(count)}</b></div><div className="ad-track"><span style={{width:`${count/max*100}%`}}/></div></div>)}</div>:<p className="ad-muted">{empty||'Noch keine Daten vorhanden.'}</p>}

function JobDetail({job,providers,request,onSaved,onClose,token,now}){
  const dialog=useRef(null),[provider,setProvider]=useState(job.provider_id||''),[status,setStatus]=useState(job.status),[note,setNote]=useState(job.admin_note||''),[saving,setSaving]=useState(false),[error,setError]=useState('')
  useEffect(()=>{dialog.current?.showModal()},[])
  async function save(e){e.preventDefault();setSaving(true);setError('');try{await request(`/jobs/${job.id}`,{method:'PATCH',body:JSON.stringify({provider_id:provider?Number(provider):null,status,admin_note:note})});onSaved()}catch(err){setError(err.message);setSaving(false)}}
  return <dialog className="ad-dialog" ref={dialog} aria-labelledby="ad-detail-title" onCancel={e=>{e.preventDefault();if(!saving)onClose()}}><div className="ad-detail-head"><div><span className="ad-eyebrow">AUFTRAG #{String(job.id).padStart(4,'0')}</span><h2 id="ad-detail-title">{job.title}</h2><Badge status={job.status}/></div><button className="ad-icon" aria-label="Auftragsdetails schließen" disabled={saving} onClick={onClose}><X/></button></div>
    <div className="ad-detail-body"><section><h3>Auftrag & Kontakt</h3><div className="ad-contact"><b>{job.contact_name}</b><a href={`mailto:${job.contact_email}`}><Mail size={15}/>{job.contact_email}</a><span><MapPin size={15}/>{job.address?`${job.address}, `:''}{job.postal_code} {job.city}</span></div><dl className="ad-facts"><div><dt>Eingegangen</dt><dd>{date(createdDate(job))}</dd></div><div><dt>Alter der Anfrage</dt><dd>{ageDays(job,now)} Tage</dd></div><div><dt>Wunschtermin</dt><dd>{date(job.desired_date)}</dd></div><div><dt>Leistungsbereich</dt><dd>{job.category}</dd></div></dl><h3>Beschreibung</h3><p className="ad-description">{job.description}</p><JobPhotos photos={job.photos} token={token}/></section>
    <form onSubmit={save}><h3>Auftrag koordinieren</h3><label>Dienstleister<select value={provider} disabled={saving} onChange={e=>{const value=e.target.value;setProvider(value);if(status==='open'&&value)setStatus('assigned');if(status==='assigned'&&!value)setStatus('open')}}><option value="">Noch nicht zugewiesen</option>{providers.map(p=><option key={p.id} value={p.id}>{p.company||p.name}</option>)}</select></label>{!providers.length&&<p className="ad-muted">Noch keine Dienstleister registriert.</p>}<label>Status<select value={status} disabled={saving} onChange={e=>setStatus(e.target.value)}>{Object.entries(STATUS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Interne Notiz<textarea rows={7} maxLength={5000} disabled={saving} value={note} onChange={e=>setNote(e.target.value)} placeholder="Zum Beispiel: Rückruf am Freitag, Zugang mit Hausverwaltung klären."/></label><p className="ad-muted">Nur in der Administration sichtbar.</p>{error&&<p className="ad-error" role="alert">{error}</p>}<div className="ad-detail-actions"><button type="button" className="ad-btn" disabled={saving} onClick={onClose}>Abbrechen</button><button type="submit" className="ad-btn ad-primary" disabled={saving}>{saving?'Speichert…':'Änderungen speichern'}<Check size={16}/></button></div></form></div>
  </dialog>
}

export default function AdminPortal({user,request,Logo,onLogout,token}){
  const [tab,setTab]=useState('overview'),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[status,setStatus]=useState('open'),[search,setSearch]=useState(''),[sort,setSort]=useState('priority'),[selected,setSelected]=useState(null),[notice,setNotice]=useState('')
  const pending=useRef(false)
  async function refresh(){if(pending.current)return;pending.current=true;setRefreshing(true);try{setData(await request('/admin/dashboard'));setError('')}catch(err){setError(err.message)}finally{pending.current=false;setLoading(false);setRefreshing(false)}}
  useEffect(()=>{refresh()},[])
  useEffect(()=>{window.scrollTo(0,0)},[tab])
  function openOrders(nextStatus){setStatus(nextStatus);setSearch('');setTab('orders')}
  const jobs=data?.jobs||[],providers=data?.providers||[],now=data?.updated_at||new Date().toISOString(),m=metrics(jobs,now)
  const filtered=filterJobs(jobs,{status,search,sort},now),priority=filterJobs(jobs,{status:'open',sort:'priority'},now).slice(0,6)
  const tabs=[['overview','Übersicht',LayoutDashboard],['orders','Aufträge',ClipboardList],['analytics','Zahlen & Fakten',BarChart3],['partners','Dienstleister',Users]]
  function JobTable({rows,empty}){return rows.length?<div className="ad-table-wrap"><table className="ad-table"><thead><tr><th>Auftrag / Kontakt</th><th>Ort</th><th>Eingang</th><th>Status</th><th>Partner</th><th><span className="ad-sr">Details</span></th></tr></thead><tbody>{rows.map(j=><tr key={j.id}><td><span className="ad-id">#{String(j.id).padStart(4,'0')}</span><button className="ad-title-link" onClick={()=>setSelected(j)}>{j.title}</button><small>{j.contact_name}</small>{overdue(j,now)&&<span className="ad-warning">Wunschtermin überschritten</span>}{j.status==='open'&&ageDays(j,now)>=3&&<span className="ad-warning">Seit {ageDays(j,now)} Tagen offen</span>}</td><td>{j.city}<small>{j.postal_code}</small></td><td>{date(createdDate(j))}</td><td><Badge status={j.status}/></td><td>{providers.find(p=>p.id===j.provider_id)?.company||providers.find(p=>p.id===j.provider_id)?.name||'Nicht zugewiesen'}</td><td><button className="ad-icon" aria-label={`Auftrag ${j.id} öffnen`} onClick={()=>setSelected(j)}><ArrowUpRight size={18}/></button></td></tr>)}</tbody></table></div>:<div className="ad-empty"><Check size={26}/><h3>{empty||'Keine passenden Aufträge'}</h3><p>{jobs.length?'Ändere die Filter oder suche nach einem anderen Begriff.':'Sobald Anfragen eingehen, erscheinen sie hier.'}</p></div>}
  return <div className="ad-shell"><aside className="ad-sidebar"><Logo/><div className="ad-brand-caption">ADMINISTRATION</div><nav aria-label="Adminnavigation">{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setNotice('')}}><Icon size={19}/>{label}{key==='orders'&&!!m.counts.open&&<span>{m.counts.open}</span>}</button>)}</nav><div className="ad-sidebar-bottom"><ShieldCheck size={20}/><span>Administrativer Zugang<small>{user.email}</small></span><a href="#/">Zur Website <ArrowUpRight size={14}/></a><button onClick={onLogout}><LogOut size={16}/>Abmelden</button></div></aside>
    <main className="ad-main"><header className="ad-topbar"><span>MACHBAR / {tabs.find(t=>t[0]===tab)?.[1]}</span><div><span className="ad-live-dot"/>Geschäftsübersicht</div></header><div className="ad-content"><div className="ad-page-title"><div><span className="ad-eyebrow">DEIN UNTERNEHMEN IM BLICK</span><h1>{tab==='overview'?'Heute zählt, was offen ist.':tabs.find(t=>t[0]===tab)?.[1]}</h1><p>{data?`Stand: ${new Date(data.updated_at).toLocaleString('de-DE')}`:'Daten werden geladen…'}</p></div><button className="ad-btn" disabled={refreshing} onClick={refresh}><RefreshCw size={16}/>{refreshing?'Lädt…':'Aktualisieren'}</button></div>
      {error&&<p className="ad-error" role="alert">{error} {data&&'Die zuletzt geladenen Daten werden weiterhin angezeigt.'}</p>}{notice&&<p className="ad-notice" role="status">{notice}</p>}
      {loading?<div className="ad-empty">Dashboard wird geladen…</div>:!data?<div className="ad-empty"><h2>Dashboard nicht verfügbar</h2><p>Bitte erneut aktualisieren oder neu anmelden.</p></div>:<>
      {tab==='overview'&&<><section className="ad-kpis" aria-label="Kennzahlen"><button className="ad-kpi ad-kpi-red" onClick={()=>openOrders('open')}><span><ClipboardList size={19}/>Offene Anfragen</span><strong>{number(m.counts.open)}</strong><small>{m.waiting} davon seit mindestens 3 Tagen offen</small></button><button className="ad-kpi" onClick={()=>openOrders('unassigned')}><span><Users size={19}/>Ohne Dienstleister</span><strong>{number(m.unassigned)}</strong><small>Nicht abgeschlossene Aufträge</small></button><button className="ad-kpi" onClick={()=>openOrders('in_progress')}><span><BriefcaseBusiness size={19}/>In Bearbeitung</span><strong>{number(m.counts.in_progress)}</strong><small>{m.counts.assigned} weitere bereits zugewiesen</small></button><button className="ad-kpi" onClick={()=>openOrders('overdue')}><span><Clock3 size={19}/>Termin überschritten</span><strong>{number(m.overdue)}</strong><small>Offener Wunschtermin liegt in der Vergangenheit</small></button></section>
        <section className="ad-panel"><div className="ad-panel-head"><div><h2>Offene Aufträge zuerst</h2><p>Überschrittene Wunschtermine zuerst, danach die ältesten Anfragen.</p></div><button className="ad-text-btn" onClick={()=>openOrders('open')}>Alle offenen ansehen <ArrowUpRight size={16}/></button></div><JobTable rows={priority} empty="Aktuell keine offenen Anfragen"/></section>
        <div className="ad-two-cols"><section className="ad-panel ad-panel-pad"><h2>Neue Anfragen</h2><p className="ad-muted">Letzte 14 Kalendertage · Tagesgrenzen in UTC</p><div className="ad-chart" aria-label="Anfragen pro Tag">{m.trend.map(t=><div key={t.date} title={`${date(t.date)}: ${t.count} Anfragen`}><b>{t.count}</b><span style={{height:`${Math.max(2,t.count/Math.max(1,...m.trend.map(x=>x.count))*120)}px`}}/><small>{t.date.slice(8)}</small></div>)}</div></section><section className="ad-panel ad-panel-pad"><h2>Gefragte Leistungen</h2><p className="ad-muted">Anzahl der Aufträge je Leistung · gesamter Zeitraum</p><Ranking items={m.services}/></section></div></>}
      {tab==='orders'&&<section className="ad-panel"><div className="ad-panel-head"><div><h2>Auftragsübersicht</h2><p>{filtered.length} von {jobs.length} Aufträgen</p></div></div><div className="ad-filters"><label className="ad-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Auftrag, Kunde, Leistung oder Ort" aria-label="Aufträge suchen"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Alle Status</option>{Object.entries(STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}<option value="unassigned">Ohne Dienstleister</option><option value="overdue">Wunschtermin überschritten</option></select></label><label>Sortierung<select value={sort} onChange={e=>setSort(e.target.value)}><option value="priority">Priorität</option><option value="newest">Neueste zuerst</option><option value="oldest">Älteste zuerst</option></select></label></div><JobTable rows={filtered}/></section>}
      {tab==='analytics'&&<><section className="ad-kpis">{[['Aufträge insgesamt',m.total,'Gesamter Zeitraum'],['Neue Anfragen',m.new30,'Letzte 30 × 24 Stunden'],['Abschlussquote',`${m.completion} %`,'Abgeschlossen / alle Aufträge'],['Ø Alter offener Anfragen',`${number(m.avgOpen)} Tage`,'Seit Eingang, nur Status „Offen“']].map(([label,value,hint])=><div className="ad-kpi" key={label}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>)}</section><div className="ad-two-cols"><section className="ad-panel ad-panel-pad"><h2>Aufträge nach Status</h2><Ranking items={Object.entries(STATUS).map(([k,v])=>[v,m.counts[k]]).sort((a,b)=>b[1]-a[1])}/></section><section className="ad-panel ad-panel-pad"><h2>Nachfrage nach Ort</h2><p className="ad-muted">Bis zu sechs häufigste Auftragsorte</p><Ranking items={m.cities}/></section><section className="ad-panel ad-panel-pad"><h2>Kunden & Netzwerk</h2><dl className="ad-stat-list">{[['Registrierte Kundenkonten',data.customers],['Eindeutige Kontakt-E-Mails in Aufträgen',m.contacts],['Registrierte Dienstleister',providers.length],['Aufträge mit Fotos',m.photoJobs],['Aktive Aufträge (ohne Abschluss)',m.active]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{number(value)}</dd></div>)}</dl></section><section className="ad-panel ad-panel-pad"><h2>Leistungen im Detail</h2><Ranking items={m.services}/><p className="ad-muted">Ein Auftrag mit mehreren Leistungen zählt bei jeder gewählten Leistung einmal.</p></section></div><p className="ad-data-note">Alle Werte stammen aus den gespeicherten Aufträgen und Konten. Umsätze, Kosten und Gewinn werden noch nicht erfasst und deshalb nicht ausgewiesen.</p></>}
      {tab==='partners'&&<section className="ad-panel"><div className="ad-panel-head"><div><h2>Dein Dienstleister-Netzwerk</h2><p>{providers.length} registrierte Partner · Auslastung nach zugewiesenen Aufträgen</p></div></div>{providers.length?<div className="ad-partner-grid">{providers.map(p=>{const list=jobs.filter(j=>j.provider_id===p.id);return <article key={p.id}><div className="ad-partner-icon"><Users size={22}/></div><h3>{p.company||p.name}</h3><p>{p.name}</p><a href={`mailto:${p.email}`}>{p.email}</a><div><span><b>{list.filter(j=>j.status!=='done').length}</b> aktiv</span><span><b>{list.filter(j=>j.status==='done').length}</b> abgeschlossen</span></div></article>})}</div>:<div className="ad-empty"><Users size={28}/><h3>Noch keine Dienstleister registriert</h3><p>Registrierte Partner erscheinen hier und können Aufträgen zugewiesen werden.</p></div>}</section>}
      </>}</div></main>{selected&&<JobDetail key={selected.id} job={selected} providers={providers} request={request} token={token} now={now} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);setNotice('Auftrag erfolgreich aktualisiert.');refresh()}}/>}
  </div>
}
