import React, {useEffect,useRef,useState} from 'react'
import {ArrowLeft,ArrowRight,Check,CheckCircle2,Mail,MapPin,Search,ShieldCheck,X} from 'lucide-react'
import {GROUPS,SERVICES,STEPS,TIMINGS,EMPTY_FORM,buildPayload,selectService,selectedGroups,needsDestination,validateStep} from './requestFlow'
import {PhotoUpload} from './JobPhotos'
import './request-wizard.css'

const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const draftKey=user=>`machbar_request_v3_${user?.id||'guest'}`
const LAST=STEPS.length-1
function readDraft(user){
  try{const saved=JSON.parse(sessionStorage.getItem(draftKey(user)));if(saved?.form&&Array.isArray(saved.form.services)&&saved.form.services.every(x=>Object.hasOwn(SERVICES,x)))return {form:{...EMPTY_FORM,...saved.form},step:Math.max(0,Math.min(LAST,Number(saved.step)||0)),hadPhotos:saved.photoCount>0}}catch{}
  return {form:{...EMPTY_FORM,services:[],scopes:{}},step:0,hadPhotos:false}
}
function Choice({label,checked,onChange,multiple=false,name='choice'}){
  return <label className={`rq-choice ${checked?'is-selected':''}`}><input type={multiple?'checkbox':'radio'} checked={checked} onChange={onChange} name={multiple?undefined:name}/><span className="rq-choice-text"><strong>{label}</strong></span><span className={`rq-indicator ${multiple?'square':''}`} aria-hidden="true">{checked&&<Check size={13}/>}</span></label>
}
function Field({label,optional,children}){return <label className="rq-field"><span>{label} {optional?<small>optional</small>:'*'}</span>{children}</label>}
function ReviewRow({label,onEdit,children}){return <div className="rq-review-row"><div><span>{label}</span><div className="rq-review-value">{children}</div></div>{onEdit&&<button type="button" className="rq-link" onClick={onEdit} aria-label={`${label} bearbeiten`}>Ändern</button>}</div>}

export default function RequestWizard({user,request,Logo}){
  const [initial]=useState(()=>readDraft(user)),[form,setForm]=useState(initial.form),[step,setStep]=useState(initial.step)
  const preselected=new URLSearchParams(location.hash.split('?')[1]||'').get('service')
  const [filter,setFilter]=useState(Object.hasOwn(GROUPS,preselected)?preselected:'Alle'),[search,setSearch]=useState('')
  const [photos,setPhotos]=useState([]),[processing,setProcessing]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null)
  const [editing,setEditing]=useState(false),[closeDialog,setCloseDialog]=useState(false)
  const heading=useRef(null),errorRef=useRef(null),submitting=useRef(false),editSnapshot=useRef(null),dialogRef=useRef(null),closeRef=useRef(null)
  const groups=selectedGroups(form),moving=needsDestination(form)
  const update=(key,value)=>{setForm(f=>({...f,[key]:value}));setError('')}
  const updateScope=(group,key,value)=>setForm(f=>({...f,scopes:{...f.scopes,[group]:{...f.scopes[group],[key]:value}}}))
  const move=next=>{setError('');setStep(next)}
  const edit=target=>{editSnapshot.current=form;setEditing(true);move(target)}
  function back(){if(editing&&editSnapshot.current)setForm(editSnapshot.current);move(editing?LAST:step-1);setEditing(false);editSnapshot.current=null}
  useEffect(()=>{if(!result)try{sessionStorage.setItem(draftKey(user),JSON.stringify({form,step,photoCount:photos.length}))}catch{}},[form,step,result,photos.length,user?.id])
  useEffect(()=>{heading.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})},[step,result])
  useEffect(()=>{if(error)errorRef.current?.focus()},[error])
  useEffect(()=>{
    if(!closeDialog)return
    const onKey=e=>{if(e.key==='Escape')setCloseDialog(false);if(e.key==='Tab'){const items=dialogRef.current?.querySelectorAll('button,a[href]');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
    window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('keydown',onKey);closeRef.current?.focus()}
  },[closeDialog])
  async function next(e){
    e.preventDefault();if(submitting.current||processing)return
    const invalid=validateStep(step,form,user,today());if(invalid){setError(invalid);return}
    if(step<LAST){move(editing?LAST:step+1);setEditing(false);return}
    for(let i=0;i<LAST;i++){const message=validateStep(i,form,user,today());if(message){move(i);setError(message);setEditing(true);editSnapshot.current=form;return}}
    submitting.current=true;setBusy(true);setError('')
    try{const response=await request('/jobs',{method:'POST',body:JSON.stringify({...buildPayload(form,user),photos:photos.map(({name,data})=>({name,data}))})});setResult(response);try{sessionStorage.removeItem(draftKey(user))}catch{}}
    catch(err){setError(err.message==='Failed to fetch'?'Die Verbindung ist unterbrochen. Deine Angaben und Fotos bleiben auf dieser Seite erhalten. Bitte versuche es erneut.':err.message)}finally{submitting.current=false;setBusy(false)}
  }
  const titles=['Was möchtest du erledigen lassen?',moving?'Wo startet dein Auftrag?':'Wo soll der Auftrag ausgeführt werden?','Wie groß ist dein Vorhaben?','Wann soll es losgehen?','Was sollten wir noch wissen?','Wie erreichen wir dich?','Passt alles so?']
  const hints=['Wähle eine oder mehrere Leistungen – auch aus unterschiedlichen Bereichen.','Wir benötigen den Ort, um passende Partner in deiner Region zu finden.','Ergänze, was du schon weißt. Alle Angaben auf dieser Seite sind freiwillig.','Der genaue Termin wird anschließend persönlich abgestimmt.','Besonderheiten und Wünsche helfen uns bei der Einschätzung. Fotos kannst du am Ende ergänzen.',user?'Wir verwenden die Kontaktdaten deines Kundenkontos.':'Für Rückfragen zu deiner Anfrage. Eine Registrierung ist nicht erforderlich.','Prüfe deine Angaben und füge bei Bedarf Fotos hinzu. Die Anfrage ist kostenlos und unverbindlich.']
  const stages=[['Leistungen',0,0],['Auftrag',1,4],['Kontakt',5,5],['Prüfen',6,6]]
  const visible=Object.entries(SERVICES).filter(([name,service])=>(filter==='Alle'||service.group===filter)&&`${name} ${service.group}`.toLocaleLowerCase('de').includes(search.toLocaleLowerCase('de')))
  return <div className="request-shell">
    <header className="rq-header"><div className="rq-header-inner"><Logo/><span className="rq-header-caption">Deine Anfrage</span><button type="button" className="rq-close" ref={closeRef} disabled={busy} onClick={()=>result?location.hash='/':setCloseDialog(true)} aria-label="Anfrage schließen"><X size={21}/></button></div></header>
    <main className="rq-main">{result?<section className="rq-success"><div className="rq-success-icon"><Check size={32}/></div><span className="rq-eyebrow">ANFRAGE #{String(result.id).padStart(4,'0')}</span><h1 ref={heading} tabIndex={-1}>Danke. Wir kümmern uns.</h1><p>Deine Anfrage mit {form.services.length} {form.services.length===1?'Leistung':'Leistungen'} in <strong>{form.city}</strong> ist eingegangen.{photos.length>0&&` ${photos.length} ${photos.length===1?'Foto wurde':'Fotos wurden'} hinzugefügt.`}</p><div className="rq-next-steps"><h2>So geht es weiter</h2><p><span>1</span>Wir prüfen deine Anfrage und suchen passende Partner.</p><p><span>2</span>Wir melden uns bei dir und stimmen Details und Termin ab.</p></div>{user?<a className="button button-red" href="#/portal">Zu meinen Aufträgen <ArrowRight size={18}/></a>:<><p>Mit einem Kundenkonto unter <strong>{form.contact_email}</strong> kannst du den Status online verfolgen.</p><a className="button button-red" href="#/register">Kundenkonto erstellen <ArrowRight size={18}/></a><a className="rq-home" href="#/">Zur Startseite</a></>}<p className="rq-help">Fragen? <a href="mailto:info.machbar@gmx.de">info.machbar@gmx.de</a></p></section>:user&&user.role!=='customer'?<section className="rq-success"><h1 ref={heading} tabIndex={-1}>Anfragen werden über ein Kundenkonto erstellt.</h1><p>Du bist als {user.role==='admin'?'Administrator':'Dienstleister'} angemeldet.</p><a className="button button-red" href="#/portal">Zum Portal</a></section>:<>
      <div className="rq-progress-head"><span>{form.services.length?`${form.services.length} ${form.services.length===1?'Leistung':'Leistungen'} ausgewählt`:'Neuer Auftrag'}</span><span>Schritt {step+1} von {STEPS.length}</span></div><div className="rq-progress" role="progressbar" aria-label="Fortschritt deiner Anfrage" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round((step+1)/STEPS.length*100)}><span style={{width:`${(step+1)/STEPS.length*100}%`}}/></div>
      <ol className="rq-stages">{stages.map(([label,start,end],i)=><li key={label} className={step>end?'complete':step>=start?'current':''} aria-current={step>=start&&step<=end?'step':undefined}><span>{step>end?<Check size={12}/>:i+1}</span>{label}</li>)}</ol>
      <div className="rq-layout"><form className="rq-form" onSubmit={next} noValidate><div className="rq-question-head"><span className="rq-eyebrow">{STEPS[step].toUpperCase()}</span><h1 ref={heading} tabIndex={-1}>{titles[step]}</h1><p>{hints[step]}</p></div>{error&&<div className="rq-error" role="alert" tabIndex={-1} ref={errorRef}>{error}</div>}
        {step===0&&<><label className="rq-search"><Search size={19}/><input type="search" aria-label="Leistung suchen" placeholder="z. B. Fenster, Streichen oder Möbel" value={search} onChange={e=>{setSearch(e.target.value);setFilter('Alle')}}/></label><div className="rq-filters" aria-label="Leistungen nach Bereich filtern">{['Alle',...Object.keys(GROUPS)].map(group=><button type="button" key={group} aria-pressed={filter===group} onClick={()=>{setFilter(group);setSearch('')}}>{group}</button>)}</div>
          {!!form.services.length&&<div className="rq-selected"><strong>Deine Auswahl ({form.services.length})</strong><div>{form.services.map(name=><button type="button" key={name} onClick={()=>setForm(f=>selectService(f,name))} aria-label={`${name} abwählen`}>{name}<X size={13}/></button>)}</div></div>}
          {Object.keys(GROUPS).map(group=>{const entries=visible.filter(([,s])=>s.group===group);return entries.length?<section className="rq-service-group" key={group}><h2>{group}</h2><div className="rq-choices">{entries.map(([name])=><Choice key={name} label={name} multiple checked={form.services.includes(name)} onChange={()=>{setForm(f=>selectService(f,name));setError('')}}/>)}</div></section>:null})}
          {!visible.length&&<div className="rq-no-results"><p>Keine passende Leistung gefunden.</p><button type="button" className="rq-link" onClick={()=>{setSearch('');setFilter('Sonstiges')}}>Anderes Anliegen auswählen</button></div>}
        </>}
        {step===1&&<><div className="rq-field-row"><Field label="Postleitzahl"><input inputMode="numeric" autoComplete="postal-code" maxLength={5} placeholder="69412" value={form.postal_code} onChange={e=>update('postal_code',e.target.value.replace(/\D/g,''))}/></Field><Field label="Ort"><input autoComplete="address-level2" maxLength={100} placeholder="Eberbach" value={form.city} onChange={e=>update('city',e.target.value)}/></Field></div><Field label="Straße und Hausnummer" optional><input autoComplete="street-address" maxLength={200} value={form.address} onChange={e=>update('address',e.target.value)}/></Field>{moving&&<div className="rq-destination"><h2>Wohin geht der Umzug oder Transport?</h2><div className="rq-field-row"><Field label="PLZ am Zielort"><input inputMode="numeric" maxLength={5} value={form.destination_postal_code} onChange={e=>update('destination_postal_code',e.target.value.replace(/\D/g,''))}/></Field><Field label="Zielort"><input maxLength={100} value={form.destination_city} onChange={e=>update('destination_city',e.target.value)}/></Field></div></div>}<div className="rq-info"><MapPin size={18}/><span>Wir starten im Raum Eberbach. Anfragen aus der Umgebung prüfen wir individuell.</span></div></>}
        {step===2&&groups.map(group=><section className="rq-scope-group" key={group}><h2>{group}</h2><p>{form.services.filter(name=>SERVICES[name].group===group).join(', ')}</p><Field label={GROUPS[group].amountLabel} optional><div className="rq-unit-input"><input type="number" min="1" max="1000000" step="any" inputMode="decimal" placeholder="Grobe Schätzung" value={form.scopes[group]?.amount||''} onChange={e=>updateScope(group,'amount',e.target.value)}/><span>{GROUPS[group].unit}</span></div></Field><fieldset className="rq-fieldset"><legend>{GROUPS[group].detailLabel} <small>optional</small></legend><div className="rq-choices">{GROUPS[group].detailChoices.map(label=><Choice key={label} label={label} name={`detail-${group}`} checked={form.scopes[group]?.detail===label} onChange={()=>updateScope(group,'detail',label)}/>)}</div>{form.scopes[group]?.detail&&<button type="button" className="rq-link rq-clear" onClick={()=>updateScope(group,'detail','')}>Angabe zurücksetzen</button>}</fieldset></section>)}
        {step===3&&<><div className="rq-choices rq-choices-single">{TIMINGS.map(label=><Choice key={label} label={label} checked={form.timing===label} onChange={()=>{setForm(f=>({...f,timing:label,desired_date:label==='An einem bestimmten Tag'?f.desired_date:''}));setError('')}}/>)}</div>{form.timing==='An einem bestimmten Tag'&&<div className="rq-date"><Field label="Dein Wunschtermin"><input type="date" min={today()} value={form.desired_date} onChange={e=>update('desired_date',e.target.value)}/></Field></div>}</>}
        {step===4&&<Field label="Zusätzliche Angaben" optional={!form.services.includes('Anderes Anliegen')}><textarea rows={6} maxLength={2000} value={form.description} placeholder="Zum Beispiel: Erst die Wohnung räumen, danach reinigen. Zugang über den Hof." onChange={e=>update('description',e.target.value)}/><small className="rq-char-count">{form.description.length} / 2.000 Zeichen</small></Field>}
        {step===5&&(user?<div className="rq-account"><CheckCircle2 size={22}/><div><strong>{user.name}</strong><span>{user.email}</span><small>Angemeldet als Kunde</small></div></div>:<><Field label="Dein Name"><input autoComplete="name" maxLength={100} value={form.contact_name} onChange={e=>update('contact_name',e.target.value)}/></Field><Field label="E-Mail-Adresse"><input type="email" autoComplete="email" maxLength={254} value={form.contact_email} onChange={e=>update('contact_email',e.target.value)}/></Field><p className="rq-contact-note">Du kannst die Anfrage ohne Registrierung absenden.</p></>)}
        {step===LAST&&<><div className="rq-review"><ReviewRow label="Leistungen" onEdit={()=>edit(0)}><ul>{form.services.map(name=><li key={name}>{name}</li>)}</ul></ReviewRow><ReviewRow label="Auftragsort" onEdit={()=>edit(1)}>{form.postal_code} {form.city}{form.address&&<small>{form.address}</small>}{moving&&<small>Ziel: {form.destination_postal_code} {form.destination_city}</small>}</ReviewRow><ReviewRow label="Umfang" onEdit={()=>edit(2)}>{groups.map(group=><div key={group}><strong>{group}</strong><small>{[form.scopes[group]?.amount&&`${form.scopes[group].amount} ${GROUPS[group].unit}`,form.scopes[group]?.detail].filter(Boolean).join(' · ')||'Noch offen'}</small></div>)}</ReviewRow><ReviewRow label="Zeitraum" onEdit={()=>edit(3)}>{form.timing}{form.desired_date&&<small>{new Date(form.desired_date+'T12:00:00').toLocaleDateString('de-DE')}</small>}</ReviewRow><ReviewRow label="Zusätzliche Angaben" onEdit={()=>edit(4)}>{form.description||'Keine weiteren Angaben'}</ReviewRow><ReviewRow label="Kontakt" onEdit={user?null:()=>edit(5)}>{user?.name||form.contact_name}<small>{user?.email||form.contact_email}</small></ReviewRow></div>{initial.hadPhotos&&!photos.length&&<p className="rq-info">Dein Textentwurf wurde wiederhergestellt. Bitte wähle die Fotos erneut aus.</p>}<PhotoUpload photos={photos} setPhotos={setPhotos} disabled={busy} onProcessing={setProcessing}/></>}
        <div className={`rq-actions ${step===0?'rq-selection-actions':''}`}>{step>0&&<button type="button" className="rq-back" disabled={busy||processing} onClick={back}><ArrowLeft size={17}/>{editing?'Abbrechen':'Zurück'}</button>}{step===0&&<span className="rq-selection-count" aria-live="polite">{form.services.length} ausgewählt</span>}<button className="button button-red rq-next" type="submit" disabled={busy||processing}>{busy?'Anfrage wird hochgeladen…':processing?'Fotos werden vorbereitet…':step===LAST?'Kostenlos Anfrage absenden':editing?'Änderung übernehmen':'Weiter'}{!busy&&<ArrowRight size={18}/>}</button></div>{step===LAST&&<p className="rq-disclosure">Mit dem Absenden speichern wir deine Angaben und Fotos zur Bearbeitung der Anfrage. Eine Beauftragung erfolgt erst nach persönlicher Abstimmung.</p>}
      </form><aside className="rq-aside"><div className="rq-aside-icon"><ShieldCheck size={23}/></div><h2>Dein Vorhaben.<br/>Eine Anfrage.</h2><p>Kombiniere die Leistungen, die du brauchst. Wir kümmern uns um die Abstimmung mit passenden Partnern.</p><ul><li><Check size={16}/>Kostenlos & unverbindlich</li><li><Check size={16}/>Persönliche Koordination</li><li><Check size={16}/>Regionale Dienstleister</li></ul><div className="rq-aside-contact"><span>Du hast eine Frage?</span><a href="mailto:info.machbar@gmx.de">info.machbar@gmx.de</a></div></aside></div>
    </>}</main><footer className="rq-footer"><span>© {new Date().getFullYear()} MACHBAR</span><a href="mailto:info.machbar@gmx.de"><Mail size={14}/>Kontakt</a></footer>
    {closeDialog&&<div className="rq-dialog-backdrop"><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="rq-exit-title" className="rq-dialog"><h2 id="rq-exit-title">Anfrage später fortsetzen?</h2><p>Deine Textangaben bleiben in diesem Browser-Tab gespeichert. Ausgewählte Fotos musst du beim nächsten Öffnen erneut hinzufügen.</p><div><button autoFocus type="button" className="button button-red" onClick={()=>setCloseDialog(false)}>Weiter ausfüllen</button><a href="#/" className="rq-link">Zur Startseite</a></div></section></div>}
  </div>
}
